# Generated by Django 4.0.6 on 2022-08-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0002_alter_watchlistitem_current_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlistitem',
            name='image_url',
            field=models.URLField(default='https://www.imageurl.com/'),
        ),
    ]
