# Generated by Django 4.0.6 on 2022-08-11 15:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0003_watchlistitem_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlistitem',
            name='price_changes',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True), blank=True, null=True, size=None), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
