# Generated by Django 4.0.6 on 2022-08-11 15:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0004_alter_watchlistitem_price_changes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlistitem',
            name='price_changes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True), size=None),
        ),
    ]
