# Generated by Django 4.0.6 on 2022-08-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0005_alter_watchlistitem_price_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlistitem',
            name='image_url',
            field=models.URLField(),
        ),
    ]
